
spring:
  application:
        name: service-redis

  redis:
    database: 0
    host: 120.0.0.1
    port: 6379
    password: 123456
    timeout: 3000
server:
  port: 10201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/
